services:
  backend:
    build: ./backend
    ports:
      - "27017:27017"
      - "3307:3306"
    depends_on:
      - mongo-db
      - mysql-db
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/workouts
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=workouts
    networks:
      - app-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: de!ta52C0y0te
      MYSQL_DATABASE: workouts
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mysql-data: